mysql:
  image: mysql:5.6.38
  ports:
    - "3306:3306"
  volumes:
    - ./mysql.sh:/docker-entrypoint-initdb.d/mysql.sh
  environment:
    - MYSQL_ROOT_PASSWORD=querydsl
    - MYSQL_USER=querydsl
    - MYSQL_PASSWORD=querydsl

postgresql:
  image: mdillon/postgis:9.3-alpine
  ports:
    - "5433:5432"
  volumes:
    - ./postgresql.sql:/docker-entrypoint-initdb.d/postgresql.sql
  environment:
    - POSTGRES_USER=querydsl
    - POSTGRES_PASSWORD=querydsl
    - POSTGRES_DB=querydsl

oracle:
  image: wnameless/oracle-xe-11g:16.04
  ports:
    - "1521:1521"

cubrid:
  image: lighthopper/cubrid:9.2.26.0004
  ports:
    - "33000:33000"
    - "30000:30000"
    - "8001:8001"
    - "8002:8002"
    - "1523:1523"

mongo:
  image: mongo:3.6.1
  ports:
    - "27017:27017"

db2:
  image: ibmcom/db2express-c:10.5.0.5-3.10.0
  ports:
    - "50000:50000"
  environment:
    - DB2INST1_PASSWORD=a3sd!fDj
    - LICENSE=accept
  command: db2start

firebird:
  image: jacobalberty/firebird:2.5.6-ss
  ports:
    - "3050:3050"
  environment:
    - ISC_PASSWORD=masterkey
    - FIREBIRD_DATABASE=querydsl.fdb
    - FIREBIRD_USER=querydsl
    - FIREBIRD_PASSWORD=querydsl
